bypassing token with regulaer url to test it

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -79,6 +79,12 @@ jobs:
         run: |
             set -e  
             set -o pipefail  
+            # Verify PAT is available (debug)
+            if [ -z "${{ secrets.GH_PAT }}" ]; then
+              echo "ERROR: GH_PAT secret is not set!"
+              exit 1
+             fi
+
             IMAGE_TAG="${GITHUB_SHA::7}"
             
             # Update Helm values
@@ -89,11 +95,19 @@ jobs:
             git config --global user.name "GitHub Actions"
             git config --global user.email "${{ secrets.GIT_COMMITTER_EMAIL }}"
             
-            # Use your GH_PAT token for authentication
-            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/aia89/hawk-challenge.git
+            # URL for authentication
+            git remote set-url origin git@github.com:aia89/hawk-challenge.git
+
+            # NEW: Add GitHub to known hosts
+            mkdir -p ~/.ssh
+            echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> ~/.ssh/known_hosts
+            
+            # NEW: Use SSH key for authentication
+            echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
+            chmod 600 ~/.ssh/id_ed25519
             
             # Commit and push
             git add helm-chart/values.yaml
             git commit -m "Update image tag to ${IMAGE_TAG} [skip ci]" || echo "Nothing to commit"
-            git push
+            git push  origin main
       
